title: Monitor feedback reconfig
description: Monitoring and Feedback Gathering Platform of SUPERSEDE project
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
